name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install & build
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCOREYOURGOALS_EBCA0 }}
        run: |
          npx firebase-tools deploy \
            --only hosting \
            --project scoreyourgoals-ebca0 \
            --token "$FIREBASE_TOKEN"
